apiVersion: v1
kind: Secret
metadata:
  name: attendance-secrets
  namespace: attendance-system
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_hMtrjxz9qA5C@ep-green-pine-anw2pzja-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require"
  SECRET_KEY: "67aa5288c88bf4499d778514fc114d79e9dfda01dac601cb15cd88f9194e78de"
  POSTGRES_USER: "neondb_owner"
  POSTGRES_PASSWORD: "TvWeIamunxz9B+pEV6g4O7h0rd4GGk4+zxVVLTQF0g4="
  POSTGRES_DB: "neondb"
